"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Auth
    login_title: "Login to continue",
    login_subtitle: "Use your email to continue",
    signup_title: "Create an account",
    signup_subtitle: "Use your email to continue",
    email_placeholder: "Email",
    password_placeholder: "Password",
    fullname_placeholder: "Full name",
    continue: "Continue",
    no_account: "Don't have an account?",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    sign_up: "Sign up",
    sign_in: "Sign in",
    invalid_credentials: "Invalid email or password",
    logged_in: "Logged in successfully",
    registration_successful: "Registration Successful!",
    check_email_confirm: "Check your email to confirm your account",
    confirmation_email_sent: "We've sent a confirmation email to",
    check_inbox_activate:
      "Please check your inbox and click the confirmation link to activate your account.",
    go_to_signin: "Go to Sign In",

    // Navigation
    features: "Features",
    pricing: "Pricing",
    documentation: "Documentation",
    settings: "Settings",
    whats_new: "What's new?",
    no_news: "No updates yet.",
    account: "Account",
    team_members: "Team Members",
    feedback: "Feedback",
    suggest_features: "Suggest Features",
    roadmap: "Roadmap",
    support: "Support",
    knowledge_base: "Knowledge Base",
    system_status: "System Status",
    login: "Login",
    start_free: "Start Free",

    // Homepage
    v2_available: "v2.0 now available",
    renders_generated: "renders generated",
    hero_title: "Create Amazing Designs at Scale with a",
    hero_title_highlight: "Simple API",
    hero_subtitle:
      "Automate your creative workflow. Integrate design tools directly into your tech stack and generate dynamic visuals in seconds.",
    btn_start_free: "Start Free",
    btn_live_demo: "Live Demo",
    how_it_works: "How It Works",
    infinite_variations: "One Design, Infinite Variations",
    demo_subtitle:
      "Test our API live. Modify the fields below and watch the design change in real-time:",
    live_preview: "Live Preview",
    modify_elements: "Modify Elements",
    modify_elements_desc: "Edit the values and see changes instantly:",
    main_title: "Main Title",
    design_btn: "Design",
    json_btn: "JSON",
    secondary_title: "Secondary Title",
    subtitle: "Subtitle",
    price: "Price",
    image_url: "Image URL",
    accent_color: "Accent Color",
    try_full_api: "Try Full API",
    dog: "Dog",
    cat: "Cat",
    donut: "Donut",
    // Admin Panel
    admin: "Admin",
    admin_panel: "Admin Panel",
    admin_panel_desc: "Manage users, templates, and platform resources",
    designs: "Designs",
    designs_desc: "Upload and manage design templates",
    upload_designs: "Upload Designs",
    uploading: "Uploading...",
    no_designs_yet: "No designs yet",
    upload_first_design: "Upload your first design to get started",
    add_design: "Add Design",
    preview: "Preview",
    design_deleted: "Design deleted",
    failed_delete_design: "Failed to delete design",
    total_users: "Total Users",
    total_templates: "Total Templates",
    total_projects: "Total Renders",
    active_api_keys: "Active API Keys",
    this_month: "this month",
    search_users: "Search by name or email...",
    all_roles: "All roles",
    user_role: "User",
    admin_role: "Admin",
    superadmin_role: "Super Admin",
    templates_created: "templates created",
    active_projects: "active projects",
    api_key_configured: "API Key configured",
    no_api_key: "No API Key",
    contact: "Contact",
    view_full_profile: "View Full Profile",
    change_role: "Change Role",
    no_users_found: "No users found",
    registration: "Registration",
    actions: "Actions",
    // Additional Admin translations
    no_name: "No name",
    active: "Active",
    recent_templates: "Recent Templates",
    view_all: "View all",
    active_projects_label: "Active Projects",
    projects_count: "projects",
    view_projects: "View projects",
    manage: "Manage",
    role: "Role",
    templates: "Templates",
    projects: "Projects",
    integrations_title: "Integrate with your favorite tools",
    integrations_subtitle:
      "Connect Dynamic Canvas with n8n, Make, Zapier and more",
    use_directly: "Or use directly from any programming language:",
    desserts: "Desserts",
    italian_food: "Italian Food",
    pet_shop: "Pet Shop",
    sweet_subtitle: "Fresh donuts made daily",
    pizza_subtitle: "Made with love from Italy",
    pet_subtitle: "Everything your pet needs",

    // Core Capabilities Section
    core_capabilities: "Core Capabilities",
    power_workflow: "Power Your Workflow",
    power_workflow_desc:
      "Tools designed by developers for developers who don't want to compromise on visual quality.",
    visual_editor: "Visual Pro Editor",
    visual_editor_desc:
      "Drag and drop capabilities for your creative team to design without touching a single line of code.",
    live_templates: "Live Templates",
    live_templates_desc:
      "Dynamic variables inside your design files. Change texts, images and colors in real time.",
    flash_rendering: "Flash Rendering",
    flash_rendering_desc:
      "Image generation in less than a second thanks to our distributed rendering engine.",
    enterprise_security: "Enterprise Security",
    enterprise_security_desc:
      "Advanced authentication, end-to-end encryption and global regulatory compliance.",

    // CTA Section
    ready_automate: "Ready to automate your design?",
    ready_automate_desc:
      "Join thousands of developers already scaling their visual production without friction. Start today for free.",
    start_free_now: "Start Free Now",
    talk_to_sales: "Talk to Sales",

    // Footer
    footer_tagline:
      "The definitive programmatic design infrastructure for modern digital products.",
    product: "Product",
    api_reference: "API Reference",
    changelog: "Changelog",
    resources: "Resources",
    community: "Community",
    guides: "Guides",
    status: "Status",
    legal: "Legal",
    privacy: "Privacy",
    terms: "Terms",
    security: "Security",
    all_rights: "All rights reserved.",
    design: "Design",

    // Theme
    light_mode: "Light mode",
    dark_mode: "Dark mode",

    // Dashboard
    my_templates: "My Templates",
    create_template: "Create template",
    search_placeholder: "Search templates...",
    no_results_found: "No templates found",
    open_in_editor: "Open in Editor",
    pixels: "pixels",
    save_preview: "Save to generate preview",
    delete_project: "Delete project",
    delete_project_confirm: "Are you sure you want to delete this project?",
    delete: "Delete",
    cancel: "Cancel",
    edit: "Edit",
    copy: "Make a copy",
    copy_postfix: " - Copy",
    api_integration: "Playground",
    api_key: "API Key",

    // Templates Section
    start_from_template: "Start from a template",
    popular: "Popular",
    social_media: "Social Media",
    presentations: "Presentations",
    documents: "Documents",
    business_marketing: "Business & Marketing",
    print_documents: "Print & Documents",
    custom_size: "Custom Size",
    define_dimensions: "Define dimensions",
    choose_preset: "Choose a preset size for your new template.",
    enter_dimensions: "Enter your desired width and height in pixels.",
    create_template_button: "Create Template",
    template_limit_free: "You've reached the 3 template limit of the free plan. Upgrade to create more.",
    template_limit_plan: "You've reached the template limit of your plan. Upgrade to create more.",
    template_limit_upgrade: "See pricing",
    choose_category: "Select a category to get started",
    creating: "Creating...",
    back: "Back",
    export_canva: "From Canva",
    export_image: "From Image",
    ai_generator: "AI Generator",
    coming_soon: "Coming Soon",
    width: "Width",
    height: "Height",
    size: "size",
    sizes: "sizes",

    // API Integration
    api_integration_title: "API Documentation",
    api_integration_desc:
      "Generate images dynamically with our REST API. Perfect for automation, integrations, and batch processing.",
    quick_start: "Quick Start",
    quick_start_step1: "Get API Key",
    quick_start_step1_desc: "Copy your key below",
    quick_start_step2: "Create Template",
    quick_start_step2_desc: "Design in the editor",
    quick_start_step3: "Call API",
    quick_start_step3_desc: "Send POST request",
    quick_start_step4: "Get Image",
    quick_start_step4_desc: "Receive rendered image",
    api_playground: "API Playground",
    api_playground_desc:
      "Test the API in real-time. Select a template, modify the JSON, and see the result.",
    template: "Template",
    request_body: "Request Body",
    reset: "Reset",
    run_request: "Generate Render",
    rendering: "Rendering...",
    generated_image: "Generated Image",
    generated_image_placeholder:
      "The generated image will appear here after running a request.",
    api_status: "Status",
    code_examples: "Code Examples",
    code_examples_desc:
      "Copy the code to integrate the API into your application.",
    simple_code: "Simple Code",
    simple_code_desc:
      "Copy only what you need. This is just the JSON payload - use it with your favorite HTTP client.",
    full_code: "Full Code",
    template_id: "Template ID",
    layers_object: "Layers Object",
    full_request_payload: "Full Request Payload",
    api_reference_title: "API Reference",
    overview: "Overview",
    request: "Request",
    response: "Response",
    errors: "Errors",
    endpoint: "Endpoint",
    authentication: "Authentication",
    authentication_desc: "Include your API key in the Authorization header:",
    api_features: "Features",
    feature_text: "Dynamic text replacement with custom colors and fonts",
    feature_image: "Image substitution with automatic scaling",
    feature_multiline: "Multi-line text support with auto-height adjustment",
    feature_centering: "Automatic centering when content grows",
    feature_cdn: "Cloud storage with CDN delivery",
    request_body_title: "Request Body",
    request_body_desc: "Send a JSON object with the following structure:",
    templateid_required: "The ID of the template to render.",
    layers_optional:
      "Object containing element IDs and their updates. Each key is an element ID from your template.",
    text_properties: "Text Element Properties",
    image_properties: "Image Element Properties",
    success_response: "Success Response (200)",
    error_responses: "Error Responses",
    unauthorized: "Unauthorized",
    unauthorized_desc: "Missing or invalid API key",
    bad_request: "Bad Request",
    bad_request_desc: "Missing templateId or invalid request format",
    not_found: "Not Found",
    not_found_desc: "Template not found",
    server_error: "Server Error",
    server_error_desc: "Internal server error during rendering",
    error_missing_templateid: "Missing templateId",
    error_missing_templateid_desc:
      "Ensure you include the templateId in your request body.",
    error_invalid_apikey: "Invalid API Key",
    error_invalid_apikey_desc:
      "Check that your API key is correct and included in the Authorization header.",
    error_element_not_found: "Element Not Found",
    error_element_not_found_desc:
      "Make sure the element ID exists in your template. Check your template's layer IDs.",
    error_image_load: "Image Load Failed",
    error_image_load_desc:
      "Ensure the image URL is accessible and returns a valid image format (PNG, JPG, etc).",
    select_template: "Select Template",
    choose_template_desc: "Choose a template to use.",
    select_a_template_placeholder: "Select a template",
    api_endpoint: "API Endpoint",
    api_endpoint_desc: "Use this endpoint from n8n, Zapier, or any HTTP client",
    endpoint_url: "Endpoint URL",
    test_endpoint: "Test Endpoint",
    testing: "Testing...",
    generated_result: "Generated Result",
    open_original_image: "Open Original Image",
    auth_validated: "Authentication: API Key validated",
    method_post: "Method: POST",
    response_processed: "Response: Processed template data",
    image_rendering_soon: "Image Rendering: Active",
    api_how_it_works: "How It Works",
    step_1_desc: "Send a POST request to /api/render with your API key",
    step_2_desc: "Include the templateId and optional layers data",
    step_3_desc: "The API validates your key and fetches the template",
    step_4_desc: "Dynamic data is merged with template elements",
    step_5_desc: "Response includes processed template data (and image URL)",
    code_snippets: "Code Snippets",
    playground_json: "Playground (JSON)",
    modify_json_hint: "Modify this JSON to test different layers and values.",
    view_copy_json_hint: "View and copy JSON for all your templates.",
    no_templates_found: "No templates found. Create one from the dashboard!",
    copy_json: "Copy JSON",
    copied: "Copied!",
    copy_failed: "Copy Failed",
    api_key_copied: "API Key Copied!",
    endpoint_url_copied: "Endpoint URL Copied!",
    api_success: "API Request Successful!",
    api_failed: "API Request Failed",

    // Sidebar
    home: "Home",
    // projects and templates are already defined in Admin section
    brand: "Brand",

    // User Menu
    log_out: "Log out",

    // Editor
    menu_file: "File",
    menu_open: "Open",
    menu_open_json_desc: "Open a JSON file",
    tool_select: "Select",
    tool_undo: "Undo",
    tool_redo: "Redo",
    tool_save: "Save",
    status_saving: "Saving...",
    status_saved: "Saved",
    status_failed_save: "Failed to save",
    menu_export: "Export",
    export_json: "JSON",
    export_json_desc: "Save for later editing",
    export_png: "PNG",
    export_png_desc: "Best for sharing on the web",
    export_jpg: "JPG",
    export_jpg_desc: "Best for printing",
    export_svg: "SVG",
    export_svg_desc: "Best for editing in vector software",
    tool_design: "Design",
    tool_image: "Image",
    tool_uploads: "Uploads",
    tool_text: "Text",
    tool_shapes: "Shapes",
    tool_vectors: "Vectors",
    tool_draw: "Draw",
    tool_qrcode: "QR Code",
    tool_barcode: "Barcode",
    tool_settings: "Settings",
    tool_color: "Color",
    tool_stroke_color: "Stroke Color",
    tool_stroke_width: "Stroke Width",
    tool_font: "Font",
    tool_bold: "Bold",
    tool_italic: "Italic",
    tool_underline: "Underline",
    tool_strike: "Strikethrough",
    tool_align_left: "Align Left",
    tool_align_center: "Align Center",
    tool_align_right: "Align Right",
    tool_vertical_align: "Vertical Align",
    tool_letter_spacing: "Letter Spacing",
    tool_line_height: "Line Height",
    tool_filters: "Filters",
    tool_effects: "Effects",
    tool_remove_bg: "Remove Background",
    tool_bring_forward: "Bring Forward",
    tool_send_backwards: "Send Backwards",
    tool_opacity: "Opacity",
    tool_duplicate: "Duplicate",
    tool_delete: "Delete",
    tool_reset_zoom: "Reset Zoom",
    tool_zoom_in: "Zoom In",
    tool_zoom_out: "Zoom Out",
    tool_align_middle: "Align Middle",
    tool_align_bottom: "Align Bottom",
    tool_align_top: "Align Top",
    tool_center_horizontally: "Center horizontally",
    tool_center_vertically: "Center vertically",

    // Navbar File Menu
    menu_unnamed_template: "Unnamed Template",
    menu_saved: "Saved",
    menu_id: "ID",
    menu_copy_template_id: "Copy template ID",
    menu_set_description: "Set description",
    menu_add_tags: "Add tags",
    menu_language: "Language",
    menu_grid: "Grid",
    menu_print_safe_zone: "Print Safe Zone",
    menu_auto_save: "Auto-save",
    menu_shortcuts: "Shortcuts",
    menu_duplicate_template: "Duplicate template",
    menu_save: "Save",
    project_saved: "Project saved",
    failed_to_save_project: "Failed to save project",
    menu_resize: "Resize",
    menu_template_dimensions: "Template Dimensions",
    menu_width: "Width",
    menu_height: "Height",
    menu_apply: "Apply",
    menu_preset_sizes: "Preset Sizes",
    menu_not_saved_yet: "Not saved yet",
    menu_just_now: "Just now",
    menu_minutes_ago: "minutes ago",
    menu_hours_ago: "hours ago",
    menu_yesterday: "Yesterday",
    menu_days_ago: "days ago",
    menu_enter_description: "Enter description:",
    menu_template_id: "Template ID",
    menu_template_id_copied: "Template ID copied to clipboard",
    menu_duplicating: "Duplicating template...",
    menu_canvas_resized: "Canvas resized to",
    menu_tags_coming_soon: "Tags feature coming soon",
    menu_shortcuts_info: "Keyboard shortcuts: Ctrl+Z (Undo), Ctrl+Y (Redo), Ctrl+S (Save), Delete (Remove)",
    menu_description_saved: "Description saved",
    menu_tags_saved: "Tags saved",

    // Preset Size Names
    preset_square: "Square",
    preset_instagram_post: "Instagram Post",
    preset_instagram_story: "Instagram Story",
    preset_landscape_post: "Landscape Post",
    preset_twitter_post: "Twitter Post",
    preset_twitter_banner: "Twitter Banner",
    preset_facebook_post: "Facebook Post",
    preset_app_store_screenshot: "App Store Screenshot",
    preset_open_graph: "Open Graph",
    preset_youtube_thumbnail: "YouTube Thumbnail",
    preset_tiktok_video: "TikTok Video",
    preset_linkedin_post: "LinkedIn Post",
    preset_billboard: "Billboard",
    preset_a4_300dpi: "A4 300dpi",
    preset_us_letter_300dpi: "US Letter 300dpi",
    preset_us_legal_300dpi: "US Legal 300dpi",

    // FloatingToolbar & ElementMenu
    floating_replace: "Replace",
    floating_border: "Border",
    floating_border_color: "Border color",
    floating_border_width: "Width",
    floating_rounded_corners: "Rounded corners",
    floating_corner_radius: "Corner radius",
    floating_flip_horizontal: "Flip horizontal",
    floating_flip_vertical: "Flip vertical",
    floating_effects: "Effects",
    floating_filters: "Filters",
    floating_remove_bg: "Remove background",
    floating_opacity: "Opacity",
    floating_center_h: "Center H",
    floating_center_v: "Center V",
    floating_font: "Font",
    floating_align_h: "Align H",
    floating_align_v: "Align V",
    floating_lock: "Lock",
    floating_unlock: "Unlock",
    floating_duplicate: "Duplicate",
    floating_delete: "Delete",
    floating_reset: "Reset",
    floating_layer_text: "Text",
    floating_layer_rect: "Rectangle",
    floating_layer_circle: "Circle",
    floating_layer_triangle: "Triangle",
    floating_layer_diamond: "Diamond",
    floating_layer_image: "Image",
    floating_layer_path: "Path",
    floating_layer_element: "Element",

    // Text Sidebar
    sidebar_text_title: "Text",
    sidebar_text_desc: "Add text to your canvas",
    add_textbox: "Add a textbox",
    add_heading: "Add a heading",
    add_subheading: "Add a subheading",
    add_paragraph: "Add a paragraph",

    // Image Sidebar
    sidebar_images_title: "Images",
    sidebar_images_desc: "Search images from Pixabay gallery",
    sidebar_images_gallery_desc: "Search images from the Pixabay gallery",
    upload_image: "Upload Image",
    // uploading already defined in Admin section
    image_uploaded: "Image uploaded!",
    image_upload_failed: "Failed to upload image",
    image_fetch_failed: "Failed to fetch images",
    my_images: "My Images",
    gallery_images: "Gallery Images",
    powered_by_pixabay: "Powered by Pixabay",
    no_images_yet: "No images yet. Upload your first image!",
    refresh: "Refresh",
    search_images: "Search images...",
    search: "Search",
    search_results: "Search results",
    // no_results_found already defined in Dashboard section
    clear_search: "Clear search",

    // Uploads Sidebar
    sidebar_uploads_title: "My Uploads",
    sidebar_uploads_desc: "Upload and manage your own images",
    loading_uploads: "Loading images...",
    uploads_error: "Error loading images",
    try_again: "Try again",
    no_uploads_yet: "No uploads yet",
    upload_first_hint: "Click the button above to upload your first image",
    images_count: "images",
    delete_image: "Delete image",
    image_deleted: "Image deleted",
    image_delete_failed: "Failed to delete image",

    // Template Sidebar
    sidebar_templates_title: "Templates",
    sidebar_templates_desc: "Choose from a variety of templates to get started",
    templates_fetch_failed: "Failed to fetch templates",
    confirm_replace_template_title: "Are you sure?",
    confirm_replace_template_desc:
      "You are about to replace the current project with this template.",

    // Filter Sidebar
    sidebar_filters_title: "Filters",
    sidebar_filters_desc: "Apply a filter to selected image",

    // Settings Sidebar
    sidebar_settings_title: "Settings",
    sidebar_settings_desc: "Change the look of your workspace",

    resize: "Resize",

    // AI Sidebar
    sidebar_ai_title: "AI",
    sidebar_ai_desc: "Generate an image using AI",
    sidebar_ai_placeholder:
      "An astronaut riding a horse on mars, hd, dramatic lighting",
    generate: "Generate",
    ai_description: "Generate images with artificial intelligence",
    // coming_soon already defined in Templates section
    ai_coming_soon_desc:
      "AI image generation is currently under development. Stay tuned for this exciting feature!",

    // Draw Sidebar
    sidebar_draw_title: "Drawing mode",
    sidebar_draw_desc: "Modify brush settings",
    brush_width: "Brush width",

    // Cookie Consent
    cookie_title: "Cookie Settings",
    cookie_description:
      "We use cookies to improve your experience, analyze site traffic, and personalize content. By clicking 'Accept', you consent to our use of cookies.",
    cookie_learn_more: "Learn more",
    cookie_accept: "Accept",
    cookie_decline: "Decline",

    // Documentation
    docs_documentation: "Documentation",
    docs_getting_started: "Getting Started",
    docs_introduction: "Introduction",
    docs_quick_start: "Quick Start",
    docs_authentication: "Authentication",
    docs_api_reference: "API Reference",
    docs_api_overview: "API Overview",
    docs_render_endpoint: "Render Endpoint",
    docs_templates: "Templates",
    docs_modifications: "Modifications",
    docs_formats: "Output Formats",
    docs_errors: "Error Handling",
    docs_guides: "Guides",
    docs_creating_templates: "Creating Templates",
    docs_dynamic_images: "Dynamic Images",
    docs_dynamic_text: "Dynamic Text",
    docs_batch_processing: "Batch Processing",
    docs_integrations: "Integrations",
    docs_n8n: "n8n",
    docs_zapier: "Zapier",
    docs_make: "Make (Integromat)",
    docs_sdks: "SDKs & Libraries",
    docs_limits: "Limits & Pricing",
    docs_rate_limits: "Rate Limits",
    docs_pricing: "Pricing",

    // Documentation Content
    docs_intro_desc: "Welcome to the Dynamic Canvas API documentation. Our REST API allows you to generate dynamic images programmatically, perfect for automating your design workflow at scale.",
    docs_new_here: "New to Dynamic Canvas?",
    docs_new_here_desc: "Start with our Quick Start guide to make your first API call in minutes.",
    docs_quick_start_desc: "Get up and running with Dynamic Canvas in three simple steps.",
    docs_step_api_key: "Get your API Key",
    docs_step_api_key_desc: "Sign up for a free account and grab your API key from the dashboard.",
    docs_step_create_request: "Create your first request",
    docs_step_create_request_desc: "Use curl or any HTTP client to make a render request.",
    docs_step_receive: "Receive your generated image",
    docs_step_receive_desc: "The API returns a URL to your generated image instantly.",
    docs_auth_desc: "All API requests require authentication using Bearer tokens. Include your API key in the Authorization header of every request.",
    docs_auth_header: "Authorization Header",
    docs_auth_header_desc: "Include your API key as a Bearer token:",
    docs_security_note: "Security Note",
    docs_security_note_desc: "Never expose your API key in client-side code or public repositories. Use environment variables to store your key securely.",
    docs_api_overview_desc: "The Dynamic Canvas API is organized around REST. Our API uses standard HTTP response codes, authentication, and verbs.",
    docs_base_url: "Base URL",
    docs_endpoints: "Available Endpoints",
    docs_endpoint_render: "Generate a new image from a template",
    docs_endpoint_templates: "List all available templates",
    docs_endpoint_template: "Get details of a specific template",
    docs_endpoint_render_status: "Check the status of a render",
    docs_render_desc: "The render endpoint is the core of our API. Send a POST request with your template ID and modifications to generate a new image.",
    docs_request_body: "Request Body",
    docs_example_request: "Example Request",
    docs_response: "Response",
    docs_templates_desc: "Templates are the foundation of your dynamic images. Use the templates endpoint to list and inspect available templates.",
    docs_modifications_desc: "Modifications allow you to customize template elements. Each modification targets a specific element by name and applies the desired change.",
    docs_mod_text: "Text Modification",
    docs_mod_text_desc: "Change the text content of text elements in your template.",
    docs_mod_image: "Image Modification",
    docs_mod_image_desc: "Replace images in your template with URLs to your own images.",
    docs_mod_color: "Color Modification",
    docs_mod_color_desc: "Update colors of elements using hex color codes.",
    docs_mod_visibility: "Visibility Modification",
    docs_mod_visibility_desc: "Show or hide elements dynamically.",
    docs_formats_desc: "Dynamic Canvas supports multiple output formats to suit your needs.",
    docs_format_png: "PNG",
    docs_format_png_desc: "Best for images with transparency. Lossless compression.",
    docs_format_jpg: "JPEG",
    docs_format_jpg_desc: "Best for photos. Smaller file size with lossy compression.",
    docs_format_webp: "WebP",
    docs_format_webp_desc: "Modern format with excellent compression. Great for web.",
    docs_format_pdf: "PDF",
    docs_format_pdf_desc: "Perfect for print materials and documents.",
    docs_errors_desc: "The API uses conventional HTTP response codes to indicate success or failure of a request.",
    docs_error_401: "Authentication Error",
    docs_error_401_desc: "Your API key is missing or invalid. Check the Authorization header.",
    docs_error_404: "Not Found",
    docs_error_404_desc: "The requested resource (template or render) was not found.",
    docs_error_422: "Validation Error",
    docs_error_422_desc: "The request body contains invalid parameters or missing required fields.",
    docs_error_429: "Rate Limit Exceeded",
    docs_error_429_desc: "You have exceeded the rate limit for your plan. Wait and retry.",
    docs_error_500: "Server Error",
    docs_error_500_desc: "An unexpected error occurred on our servers. Please try again later.",
    docs_creating_templates_desc: "Create templates using our visual editor in the dashboard. Templates define the base design that will be modified via API.",
    docs_template_steps: "Steps to Create a Template",
    docs_template_step1: "Go to the Dashboard and click 'Create Template'",
    docs_template_step2: "Design your template using the visual editor",
    docs_template_step3: "Name each element you want to modify dynamically",
    docs_template_step4: "Save and note your template ID for API calls",
    docs_dynamic_images_desc: "Replace images in your templates dynamically. Images are fetched from URLs you provide.",
    docs_supported_formats: "Supported Image Formats",
    docs_dynamic_text_desc: "Modify text elements in your templates with dynamic content.",
    docs_text_tips: "Best Practices for Dynamic Text",
    docs_text_tip1: "Use text boxes that can accommodate varying text lengths",
    docs_text_tip2: "Consider text overflow behavior in your template design",
    docs_text_tip3: "Test with realistic content to ensure proper formatting",
    docs_batch_processing_desc: "Generate multiple images efficiently by iterating through your data.",
    docs_n8n_desc: "Connect Dynamic Canvas to n8n workflows for powerful automation. Use the HTTP Request node to call our API.",
    docs_n8n_steps: "Setup Steps",
    docs_n8n_step1: "Add an HTTP Request node to your workflow",
    docs_n8n_step2: "Set method to POST and URL to our render endpoint",
    docs_n8n_step3: "Add your API key in the headers and configure the body",
    docs_zapier_desc: "Integrate Dynamic Canvas with 5000+ apps using Zapier. Create Zaps that generate images based on triggers from other apps.",
    docs_make_desc: "Use Make (formerly Integromat) to create complex automation scenarios with Dynamic Canvas.",
    docs_sdks_desc: "Use our official SDKs for faster integration in your preferred language.",
    docs_rate_limits_desc: "Rate limits vary by plan. Exceeding limits will result in 429 errors.",
    docs_plan: "Plan",
    docs_requests_min: "Requests/min",
    docs_renders_month: "Renders/month",
    docs_free: "Free",
    docs_pro: "Pro",
    docs_enterprise: "Enterprise",
    docs_unlimited: "Unlimited",
    docs_pricing_desc: "Dynamic Canvas offers flexible pricing to match your needs.",
    docs_pricing_info: "Visit the pricing page on our website for detailed plan information and features.",

    // Legal Pages
    privacy_policy: "Privacy Policy",
    terms_title: "Terms of Service",
    last_updated: "Last updated",
    back_to_home: "Back to home",

    // Privacy Policy
    privacy_intro_title: "Introduction",
    privacy_intro_desc:
      "At Dynamic Canvas, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our design automation platform and API services.",
    privacy_collect_title: "Information We Collect",
    privacy_collect_desc:
      "We may collect information about you in various ways:",
    privacy_collect_name: "Name and contact information when you create an account",
    privacy_collect_email: "Email address for account verification and communications",
    privacy_collect_usage: "Usage data including templates created and renders generated",
    privacy_collect_api: "API usage statistics and logs for service improvement",
    privacy_collect_device: "Device and browser information for security purposes",
    privacy_use_title: "How We Use Your Information",
    privacy_use_desc:
      "We use the information we collect for the following purposes:",
    privacy_use_service: "To provide and maintain our design automation services",
    privacy_use_communicate: "To communicate with you about updates, features, and support",
    privacy_use_improve: "To improve our platform and develop new features",
    privacy_use_security: "To detect and prevent fraud, abuse, and security issues",
    privacy_storage_title: "Data Storage and Security",
    privacy_storage_desc:
      "We implement appropriate technical and organizational security measures to protect your personal information. Your data is stored on secure servers with encryption at rest and in transit. We retain your information only for as long as necessary to provide our services.",
    privacy_rights_title: "Your Rights",
    privacy_rights_desc:
      "You have certain rights regarding your personal information:",
    privacy_rights_access: "Access: Request a copy of your personal data",
    privacy_rights_correct: "Correction: Request correction of inaccurate data",
    privacy_rights_delete: "Deletion: Request deletion of your data",
    privacy_rights_export: "Export: Receive your data in a portable format",
    privacy_cookies_title: "Cookies and Tracking",
    privacy_cookies_desc:
      "We use cookies and similar tracking technologies to enhance your experience on our platform. You can control cookie preferences through your browser settings. We use both session and persistent cookies for authentication, preferences, and analytics.",
    privacy_third_title: "Third-Party Services",
    privacy_third_desc:
      "We may use third-party services for payment processing, analytics, and infrastructure. These providers have their own privacy policies and we only share information necessary for them to provide their services.",
    privacy_children_title: "Children's Privacy",
    privacy_children_desc:
      "Our services are not directed to individuals under 16. We do not knowingly collect personal information from children. If you believe we have collected information from a child, please contact us.",
    privacy_changes_title: "Changes to This Policy",
    privacy_changes_desc:
      "We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the 'Last updated' date.",
    privacy_contact_title: "Contact Us",
    privacy_contact_desc:
      "If you have questions about this Privacy Policy, please contact us at:",

    // Terms of Service
    terms_intro_title: "Agreement to Terms",
    terms_intro_desc:
      "These Terms of Service constitute a legally binding agreement between you and Dynamic Canvas regarding your use of our design automation platform, API services, and related features.",
    terms_acceptance_title: "Acceptance of Terms",
    terms_acceptance_desc:
      "By accessing or using Dynamic Canvas, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.",
    terms_service_title: "Description of Service",
    terms_service_desc:
      "Dynamic Canvas provides a design automation platform that includes:",
    terms_service_templates: "Template creation and editing tools",
    terms_service_api: "REST API for programmatic image generation",
    terms_service_renders: "Dynamic rendering of designs with custom data",
    terms_service_storage: "Cloud storage for templates and generated images",
    terms_accounts_title: "User Accounts",
    terms_accounts_desc:
      "You are responsible for safeguarding the password that you use to access the service:",
    terms_accounts_accurate: "Provide accurate and complete information during registration",
    terms_accounts_security: "Maintain the security of your account credentials",
    terms_accounts_responsible: "Accept responsibility for all activities under your account",
    terms_usage_title: "Acceptable Use",
    terms_usage_desc:
      "You agree not to use the service for any unlawful purpose or in any way that could damage, disable, or impair the service. Prohibited activities include:",
    terms_usage_illegal: "Violating any applicable laws or regulations",
    terms_usage_harmful: "Distributing malware or harmful code",
    terms_usage_infringe: "Infringing on intellectual property rights of others",
    terms_usage_malicious: "Attempting to gain unauthorized access to systems",
    terms_usage_reverse: "Reverse engineering or attempting to extract source code",
    terms_usage_spam: "Using the service to send spam or unsolicited communications",
    terms_ip_title: "Intellectual Property",
    terms_ip_desc:
      "The service and its original content, features, and functionality are owned by Dynamic Canvas:",
    terms_ip_platform: "The platform, software, and underlying technology belong to Dynamic Canvas",
    terms_ip_content: "You retain ownership of content you create and upload",
    terms_ip_renders: "Generated renders from your templates belong to you",
    terms_payment_title: "Payment Terms",
    terms_payment_desc:
      "Some features require payment. You agree to provide accurate billing information and authorize us to charge your chosen payment method for the selected plan. All fees are non-refundable except as required by law.",
    terms_cancellation_title: "Cancellation and Termination",
    terms_cancellation_desc:
      "You may cancel your account at any time. Upon cancellation, your access to paid features will end at the current billing period. We may suspend or terminate your account for violations of these Terms.",
    terms_limitation_title: "Limitation of Liability",
    terms_limitation_desc:
      "Dynamic Canvas shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.",
    terms_modifications_title: "Modifications",
    terms_modifications_desc:
      "We reserve the right to modify these Terms at any time. We will provide notice of significant changes. Your continued use of the service after changes constitutes acceptance of the modified Terms.",
    terms_governing_title: "Governing Law",
    terms_governing_desc:
      "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.",
    terms_contact_title: "Contact Us",
    terms_contact_desc:
      "For questions about these Terms, please contact us at:",

    // Security Page
    security_title: "Security",
    security_intro_title: "Our Commitment to Security",
    security_intro_desc:
      "At Dynamic Canvas, security is a top priority. We implement industry-leading security practices to protect your data and ensure the reliability of our design automation platform.",
    security_infrastructure_title: "Infrastructure Security",
    security_infrastructure_desc:
      "Our infrastructure is built with security in mind:",
    security_infrastructure_hosting: "Secure cloud hosting with leading providers",
    security_infrastructure_encryption: "Encryption at rest and in transit for all data",
    security_infrastructure_backups: "Regular automated backups with secure storage",
    security_infrastructure_monitoring: "24/7 monitoring and alerting systems",
    security_api_title: "API Security",
    security_api_desc:
      "Our API is designed with multiple layers of security:",
    security_api_keys: "Secure API key authentication with scoped permissions",
    security_api_https: "All API communications use HTTPS/TLS encryption",
    security_api_rate: "Rate limiting to prevent abuse and ensure fair usage",
    security_api_audit: "Comprehensive audit logging of all API requests",
    security_data_title: "Data Protection",
    security_data_desc:
      "We protect your data through multiple measures:",
    security_data_rest: "Encryption at rest using AES-256",
    security_data_transit: "Encryption in transit using TLS 1.3",
    security_data_retention: "Configurable data retention policies",
    security_data_deletion: "Secure data deletion upon request",
    security_access_title: "Access Control",
    security_access_desc:
      "We implement strict access controls:",
    security_access_authentication: "Multi-factor authentication available",
    security_access_authorization: "Role-based access control (RBAC)",
    security_access_least: "Principle of least privilege for all access",
    security_access_logging: "Comprehensive access logging and monitoring",
    security_compliance_title: "Compliance",
    security_compliance_desc:
      "We maintain compliance with industry standards:",
    security_compliance_gdpr: "GDPR compliant for EU data protection",
    security_compliance_soc: "SOC 2 Type II certification in progress",
    security_compliance_pci: "PCI DSS compliant payment processing",
    security_incident_title: "Incident Response",
    security_incident_desc:
      "Our incident response process includes:",
    security_incident_detection: "Rapid detection and assessment",
    security_incident_response: "Immediate response and containment",
    security_incident_notification: "Transparent notification to affected users",
    security_incident_post: "Post-incident review and improvements",
    security_vulnerability_title: "Responsible Disclosure",
    security_vulnerability_desc:
      "We welcome security researchers to report vulnerabilities responsibly. If you discover a security issue, please report it to our security team with details. We are committed to addressing legitimate security concerns promptly and will acknowledge responsible disclosures.",
    security_contact_title: "Security Contact",
    security_contact_desc:
      "To report a security issue or for security-related inquiries, contact us at:",
  },
  es: {
    // Auth
    login_title: "Iniciar sesión",
    login_subtitle: "Usa tu correo para continuar",
    signup_title: "Crear una cuenta",
    signup_subtitle: "Usa tu correo para continuar",
    email_placeholder: "Correo electrónico",
    password_placeholder: "Contraseña",
    fullname_placeholder: "Nombre completo",
    continue: "Continuar",
    no_account: "¿No tienes una cuenta?",
    dont_have_account: "¿No tienes una cuenta?",
    already_have_account: "¿Ya tienes una cuenta?",
    sign_up: "Regístrate",
    sign_in: "Inicia sesión",
    invalid_credentials: "Correo o contraseña inválidos",
    logged_in: "Sesión iniciada exitosamente",
    registration_successful: "¡Registro Exitoso!",
    check_email_confirm: "Revisa tu correo para confirmar tu cuenta",
    confirmation_email_sent: "Hemos enviado un correo de confirmación a",
    check_inbox_activate:
      "Por favor revisa tu bandeja de entrada y haz clic en el enlace de confirmación para activar tu cuenta.",
    go_to_signin: "Ir a Iniciar Sesión",

    // Navigation
    features: "Características",
    pricing: "Precios",
    documentation: "Documentación",
    settings: "Ajustes",
    whats_new: "Novedades",
    no_news: "Sin novedades todavía.",
    account: "Cuenta",
    team_members: "Miembros del equipo",
    feedback: "Feedback",
    suggest_features: "Sugerir funciones",
    roadmap: "Roadmap",
    support: "Soporte",
    knowledge_base: "Base de conocimiento",
    system_status: "Estado del sistema",
    login: "Iniciar Sesión",
    start_free: "Empezar Gratis",

    // Homepage
    v2_available: "v2.0 ya disponible",
    renders_generated: "renders generados",
    hero_title: "Crea Diseños Asombrosos a Escala con una",
    hero_title_highlight: "Simple API",
    hero_subtitle:
      "Automatiza tu flujo de trabajo creativo. Integra herramientas de diseño directamente en tu stack tecnológico y genera visuales dinámicos en segundos.",
    btn_start_free: "Empezar Gratis",
    btn_live_demo: "Ver Demo",
    how_it_works: "Cómo Funciona",
    infinite_variations: "Un Diseño, Infinitas Variaciones",
    demo_subtitle:
      "Prueba nuestra API en vivo. Modifica los campos abajo y observa cómo cambia el diseño en tiempo real:",
    live_preview: "Vista Previa en Vivo",
    modify_elements: "Modifica los Elementos",
    modify_elements_desc:
      "Edita los valores y observa los cambios instantáneamente:",
    main_title: "Título Principal",
    design_btn: "Diseño",
    json_btn: "JSON",
    secondary_title: "Título Secundario",
    subtitle: "Subtítulo",
    price: "Precio",
    image_url: "URL de Imagen",
    accent_color: "Color de Acento",
    try_full_api: "Probar API Completa",
    dog: "Perro",
    cat: "Gato",
    donut: "Donut",
    // Panel de Administración
    admin: "Administrador",
    admin_panel: "Panel de Administración",
    admin_panel_desc:
      "Gestiona usuarios, plantillas y recursos de la plataforma",
    designs: "Diseños",
    designs_desc: "Sube y gestiona plantillas de diseño",
    upload_designs: "Subir Diseños",
    uploading: "Subiendo...",
    no_designs_yet: "Aún no hay diseños",
    upload_first_design: "Sube tu primer diseño para comenzar",
    add_design: "Agregar Diseño",
    preview: "Vista previa",
    design_deleted: "Diseño eliminado",
    failed_delete_design: "Error al eliminar diseño",
    total_users: "Total de Usuarios",
    total_templates: "Total de Plantillas",
    total_projects: "Total Renders",
    active_api_keys: "API Keys Activas",
    this_month: "este mes",
    search_users: "Buscar por nombre o email...",
    all_roles: "Todos los roles",
    user_role: "Usuario",
    admin_role: "Administrador",
    superadmin_role: "Super Administrador",
    templates_created: "plantillas creadas",
    active_projects: "proyectos activos",
    api_key_configured: "API Key configurada",
    no_api_key: "Sin API Key",
    contact: "Contactar",
    view_full_profile: "Ver Perfil Completo",
    change_role: "Cambiar Rol",
    no_users_found: "No se encontraron usuarios",
    registration: "Registro",
    actions: "Acciones",
    // Traducciones adicionales de Admin
    no_name: "Sin nombre",
    active: "Activa",
    recent_templates: "Plantillas Recientes",
    view_all: "Ver todas",
    active_projects_label: "Proyectos Activos",
    projects_count: "proyectos",
    view_projects: "Ver proyectos",
    manage: "Gestionar",
    role: "Rol",
    templates: "Plantillas",
    projects: "Proyectos",
    integrations_title: "Integra con tus herramientas favoritas",
    integrations_subtitle: "Conecta Dynamic Canvas con n8n, Make, Zapier y más",
    use_directly:
      "O usa directamente desde cualquier lenguaje de programación:",
    desserts: "Postres",
    italian_food: "Comida Italiana",
    pet_shop: "Tienda de Mascotas",
    sweet_subtitle: "Donuts frescos todos los días",
    pizza_subtitle: "Hecha con amor desde Italia",
    pet_subtitle: "Todo lo que tu mascota necesita",

    // Core Capabilities Section
    core_capabilities: "Capacidades Core",
    power_workflow: "Potencia tu Flujo de Trabajo",
    power_workflow_desc:
      "Herramientas diseñadas por desarrolladores para desarrolladores que no quieren comprometer la calidad visual.",
    visual_editor: "Editor Visual Pro",
    visual_editor_desc:
      "Capacidad de arrastrar y soltar para que tu equipo creativo diseñe sin tocar una sola línea de código.",
    live_templates: "Plantillas Vivas",
    live_templates_desc:
      "Variables dinámicas dentro de tus archivos de diseño. Cambia textos, imágenes y colores en tiempo real.",
    flash_rendering: "Renderizado Flash",
    flash_rendering_desc:
      "Generación de imágenes en menos de un segundo gracias a nuestro motor de renderizado distribuido.",
    enterprise_security: "Seguridad Enterprise",
    enterprise_security_desc:
      "Autenticación avanzada, cifrado de extremo a extremo y cumplimiento de normativas globales.",

    // CTA Section
    ready_automate: "¿Listo para automatizar tu diseño?",
    ready_automate_desc:
      "Únete a miles de desarrolladores que ya están escalando su producción visual sin fricción. Comienza hoy mismo gratis.",
    start_free_now: "Empezar Gratis Ahora",
    talk_to_sales: "Hablar con Ventas",

    // Footer
    footer_tagline:
      "La infraestructura de diseño programático definitiva para productos digitales modernos.",
    product: "Producto",
    api_reference: "Referencia API",
    changelog: "Changelog",
    resources: "Recursos",
    community: "Comunidad",
    guides: "Guías",
    status: "Status",
    legal: "Legal",
    privacy: "Privacidad",
    terms: "Términos",
    security: "Seguridad",
    all_rights: "Todos los derechos reservados.",
    design: "Diseño",

    // Theme
    light_mode: "Modo claro",
    dark_mode: "Modo oscuro",

    // Dashboard
    my_templates: "Mis Plantillas",
    create_template: "Crear plantilla",
    search_placeholder: "Buscar plantillas...",
    no_results_found: "No se encontraron plantillas",
    open_in_editor: "Abrir en Editor",
    pixels: "píxeles",
    save_preview: "Guarda para generar vista previa",
    delete_project: "Eliminar proyecto",
    delete_project_confirm: "¿Estás seguro que quieres eliminar este proyecto?",
    delete: "Eliminar",
    cancel: "Cancelar",
    edit: "Editar",
    copy: "Hacer una copia",
    copy_postfix: " - Copia",
    api_integration: "Playground",
    api_key: "API Key",

    // Templates Section
    start_from_template: "Empezar con una plantilla",
    popular: "Popular",
    social_media: "Redes Sociales",
    presentations: "Presentaciones",
    documents: "Documentos",
    business_marketing: "Negocios y Marketing",
    print_documents: "Impresión y Documentos",
    custom_size: "Tamaño Personalizado",
    define_dimensions: "Definir dimensiones",
    choose_preset: "Elige un tamaño predefinido para tu nueva plantilla.",
    enter_dimensions: "Ingresa el ancho y alto deseado en píxeles.",
    create_template_button: "Crear Plantilla",
    template_limit_free: "Has alcanzado el límite de 3 plantillas del plan gratuito. Mejora tu plan para crear más.",
    template_limit_plan: "Has alcanzado el límite de plantillas de tu plan. Mejora tu plan para crear más.",
    template_limit_upgrade: "Ver precios",
    choose_category: "Selecciona una categoría para comenzar",
    creating: "Creando...",
    back: "Volver",
    export_canva: "Desde Canva",
    export_image: "Desde Imagen",
    ai_generator: "Generador IA",
    coming_soon: "Próximamente",
    width: "Ancho",
    height: "Alto",
    size: "tamaño",
    sizes: "tamaños",

    // API Integration
    api_integration_title: "Documentación API",
    api_integration_desc:
      "Genera imágenes dinámicamente con nuestra API REST. Perfecto para automatización, integraciones y procesamiento por lotes.",
    quick_start: "Inicio Rápido",
    quick_start_step1: "Obtener API Key",
    quick_start_step1_desc: "Copia tu clave abajo",
    quick_start_step2: "Crear Plantilla",
    quick_start_step2_desc: "Diseña en el editor",
    quick_start_step3: "Llamar API",
    quick_start_step3_desc: "Envía petición POST",
    quick_start_step4: "Obtener Imagen",
    quick_start_step4_desc: "Recibe imagen renderizada",
    api_playground: "API Playground",
    api_playground_desc:
      "Prueba la API en tiempo real. Selecciona una plantilla, modifica el JSON y ve el resultado.",
    template: "Plantilla",
    request_body: "Cuerpo de la Petición",
    reset: "Restablecer",
    run_request: "Generar Render",
    rendering: "Renderizando...",
    generated_image: "Imagen Generada",
    generated_image_placeholder:
      "La imagen generada aparecerá aquí después de ejecutar una petición.",
    api_status: "Estado",
    code_examples: "Ejemplos de Código",
    code_examples_desc:
      "Copia el código para integrar la API en tu aplicación.",
    simple_code: "Código Simple",
    simple_code_desc:
      "Copia solo lo que necesitas. Este es solo el payload JSON - úsalo con tu cliente HTTP favorito.",
    full_code: "Código Completo",
    template_id: "ID de Plantilla",
    layers_object: "Objeto de Capas",
    full_request_payload: "Payload Completo de Petición",
    api_reference_title: "Referencia API",
    overview: "Vista General",
    request: "Petición",
    response: "Respuesta",
    errors: "Errores",
    endpoint: "Endpoint",
    authentication: "Autenticación",
    authentication_desc: "Incluye tu clave API en el header de Authorization:",
    api_features: "Características",
    feature_text:
      "Reemplazo de texto dinámico con colores y fuentes personalizadas",
    feature_image: "Sustitución de imágenes con escalado automático",
    feature_multiline:
      "Soporte de texto multilínea con ajuste automático de altura",
    feature_centering: "Centrado automático cuando el contenido crece",
    feature_cdn: "Almacenamiento en la nube con entrega CDN",
    request_body_title: "Cuerpo de la Petición",
    request_body_desc: "Envía un objeto JSON con la siguiente estructura:",
    templateid_required: "El ID de la plantilla a renderizar.",
    layers_optional:
      "Objeto que contiene IDs de elementos y sus actualizaciones. Cada clave es un ID de elemento de tu plantilla.",
    text_properties: "Propiedades de Elemento de Texto",
    image_properties: "Propiedades de Elemento de Imagen",
    success_response: "Respuesta Exitosa (200)",
    error_responses: "Respuestas de Error",
    unauthorized: "No Autorizado",
    unauthorized_desc: "Clave API faltante o inválida",
    bad_request: "Solicitud Incorrecta",
    bad_request_desc: "Falta templateId o formato de solicitud inválido",
    not_found: "No Encontrado",
    not_found_desc: "Plantilla no encontrada",
    server_error: "Error del Servidor",
    server_error_desc: "Error interno del servidor durante el renderizado",
    error_missing_templateid: "templateId faltante",
    error_missing_templateid_desc:
      "Asegúrate de incluir el templateId en el cuerpo de tu petición.",
    error_invalid_apikey: "Clave API Inválida",
    error_invalid_apikey_desc:
      "Verifica que tu clave API sea correcta y esté incluida en el header Authorization.",
    error_element_not_found: "Elemento No Encontrado",
    error_element_not_found_desc:
      "Asegúrate de que el ID del elemento exista en tu plantilla. Revisa los IDs de capa de tu plantilla.",
    error_image_load: "Error al Cargar Imagen",
    error_image_load_desc:
      "Asegúrate de que la URL de la imagen sea accesible y devuelva un formato de imagen válido (PNG, JPG, etc).",
    select_template: "Seleccionar Plantilla",
    choose_template_desc: "Elige una plantilla para usar.",
    select_a_template_placeholder: "Selecciona una plantilla",
    api_endpoint: "Endpoint de API",
    api_endpoint_desc:
      "Usa este endpoint desde n8n, Zapier, o cualquier cliente HTTP",
    endpoint_url: "URL del Endpoint",
    test_endpoint: "Probar Endpoint",
    testing: "Probando...",
    generated_result: "Resultado Generado",
    open_original_image: "Abrir Imagen Original",
    auth_validated: "Autenticación: Clave API validada",
    method_post: "Método: POST",
    response_processed: "Respuesta: Datos de plantilla procesados",
    image_rendering_soon: "Renderizado de Imagen: Activo",
    api_how_it_works: "Cómo Funciona",
    step_1_desc: "Envía una petición POST a /api/render con tu clave API",
    step_2_desc: "Incluye el templateId y datos opcionales de layers",
    step_3_desc: "La API valida tu clave y obtiene la plantilla",
    step_4_desc: "Los datos dinámicos se fusionan con los elementos",
    step_5_desc: "La respuesta incluye datos procesados (y URL de imagen)",
    code_snippets: "Fragmentos de Código",
    playground_json: "Playground (JSON)",
    modify_json_hint:
      "Modifica este JSON para probar diferentes capas y valores.",
    view_copy_json_hint: "Ver y copiar JSON para todas tus plantillas.",
    no_templates_found:
      "No se encontraron plantillas. ¡Crea una desde el panel!",
    copy_json: "Copiar JSON",
    copied: "¡Copiado!",
    copy_failed: "Fallo al copiar",
    api_key_copied: "¡Clave API Copiada!",
    endpoint_url_copied: "¡URL del Endpoint Copiada!",
    api_success: "¡Petición API Exitosa!",
    api_failed: "Petición API Fallida",

    // Sidebar
    home: "Inicio",
    // projects and templates already defined in Admin section
    brand: "Marca",

    // User Menu
    log_out: "Cerrar sesión",

    // Editor
    menu_file: "Archivo",
    menu_open: "Abrir",
    menu_open_json_desc: "Abrir un archivo JSON",
    tool_select: "Seleccionar",
    tool_undo: "Deshacer",
    tool_redo: "Rehacer",
    tool_save: "Guardar",
    status_saving: "Guardando...",
    status_saved: "Guardado",
    status_failed_save: "Error al guardar",
    menu_export: "Exportar",
    export_json: "JSON",
    export_json_desc: "Guardar para editar luego",
    export_png: "PNG",
    export_png_desc: "Mejor para web",
    export_jpg: "JPG",
    export_jpg_desc: "Mejor para imprimir",
    export_svg: "SVG",
    export_svg_desc: "Mejor para vectores de software",
    tool_design: "Diseño",
    tool_image: "Imagen",
    tool_uploads: "Subidas",
    tool_text: "Texto",
    tool_shapes: "Formas",
    tool_vectors: "Vectores",
    tool_draw: "Dibujar",
    tool_qrcode: "QR Code",
    tool_barcode: "Código Barras",
    tool_settings: "Ajustes",
    tool_color: "Color",
    tool_stroke_color: "Color Borde",
    tool_stroke_width: "Ancho Borde",
    tool_font: "Fuente",
    tool_bold: "Negrita",
    tool_italic: "Cursiva",
    tool_underline: "Subrayado",
    tool_strike: "Tachado",
    tool_align_left: "Alinear Izquierda",
    tool_align_center: "Alinear Centro",
    tool_align_right: "Alinear Derecha",
    tool_vertical_align: "Alinear Vertical",
    tool_letter_spacing: "Espaciado Letras",
    tool_line_height: "Altura Línea",
    tool_filters: "Filtros",
    tool_effects: "Efectos",
    tool_remove_bg: "Quitar Fondo",
    tool_bring_forward: "Traer al Frente",
    tool_send_backwards: "Enviar al Fondo",
    tool_opacity: "Opacidad",
    tool_duplicate: "Duplicar",
    tool_delete: "Eliminar",
    tool_reset_zoom: "Restablecer Zoom",
    tool_zoom_in: "Acercar",
    tool_zoom_out: "Alejar",
    tool_align_middle: "Alinear Medio",
    tool_align_bottom: "Alinear Abajo",
    tool_align_top: "Alinear Arriba",
    tool_center_horizontally: "Centrar horizontalmente",
    tool_center_vertically: "Centrar verticalmente",

    // Navbar File Menu
    menu_unnamed_template: "Plantilla sin nombre",
    menu_saved: "Guardado",
    menu_id: "ID",
    menu_copy_template_id: "Copiar ID de plantilla",
    menu_set_description: "Establecer descripción",
    menu_add_tags: "Agregar etiquetas",
    menu_language: "Idioma",
    menu_grid: "Cuadrícula",
    menu_print_safe_zone: "Zona de impresión segura",
    menu_auto_save: "Auto-guardado",
    menu_shortcuts: "Atajos",
    menu_duplicate_template: "Duplicar plantilla",
    menu_save: "Guardar",
    project_saved: "Proyecto guardado",
    failed_to_save_project: "Error al guardar el proyecto",
    menu_resize: "Redimensionar",
    menu_template_dimensions: "Dimensiones de Plantilla",
    menu_width: "Ancho",
    menu_height: "Alto",
    menu_apply: "Aplicar",
    menu_preset_sizes: "Tamaños Predefinidos",
    menu_not_saved_yet: "Aún no guardado",
    menu_just_now: "Recién",
    menu_minutes_ago: "minutos atrás",
    menu_hours_ago: "horas atrás",
    menu_yesterday: "Ayer",
    menu_days_ago: "días atrás",
    menu_enter_description: "Ingresa descripción:",
    menu_template_id: "ID de Plantilla",
    menu_template_id_copied: "ID de plantilla copiado al portapapeles",
    menu_duplicating: "Duplicando plantilla...",
    menu_canvas_resized: "Lienzo redimensionado a",
    menu_tags_coming_soon: "Función de etiquetas próximamente",
    menu_shortcuts_info: "Atajos de teclado: Ctrl+Z (Deshacer), Ctrl+Y (Rehacer), Ctrl+S (Guardar), Delete (Eliminar)",
    menu_description_saved: "Descripción guardada",
    menu_tags_saved: "Etiquetas guardadas",

    // Preset Size Names
    preset_square: "Cuadrado",
    preset_instagram_post: "Post de Instagram",
    preset_instagram_story: "Historia de Instagram",
    preset_landscape_post: "Post Horizontal",
    preset_twitter_post: "Post de Twitter",
    preset_twitter_banner: "Banner de Twitter",
    preset_facebook_post: "Post de Facebook",
    preset_app_store_screenshot: "Captura App Store",
    preset_open_graph: "Open Graph",
    preset_youtube_thumbnail: "Miniatura YouTube",
    preset_tiktok_video: "Video TikTok",
    preset_linkedin_post: "Post de LinkedIn",
    preset_billboard: "Valla Publicitaria",
    preset_a4_300dpi: "A4 300dpi",
    preset_us_letter_300dpi: "Carta US 300dpi",
    preset_us_legal_300dpi: "Oficio US 300dpi",

    // FloatingToolbar & ElementMenu
    floating_replace: "Reemplazar",
    floating_border: "Borde",
    floating_border_color: "Color del borde",
    floating_border_width: "Grosor",
    floating_rounded_corners: "Esquinas redondeadas",
    floating_corner_radius: "Radio de esquina",
    floating_flip_horizontal: "Voltear horizontal",
    floating_flip_vertical: "Voltear vertical",
    floating_effects: "Efectos",
    floating_filters: "Filtros",
    floating_remove_bg: "Quitar fondo",
    floating_opacity: "Opacidad",
    floating_center_h: "Centrar H",
    floating_center_v: "Centrar V",
    floating_font: "Fuente",
    floating_align_h: "Alineación H",
    floating_align_v: "Alineación V",
    floating_lock: "Bloquear",
    floating_unlock: "Desbloquear",
    floating_duplicate: "Duplicar",
    floating_delete: "Eliminar",
    floating_reset: "Restablecer",
    floating_layer_text: "Texto",
    floating_layer_rect: "Rectángulo",
    floating_layer_circle: "Círculo",
    floating_layer_triangle: "Triángulo",
    floating_layer_diamond: "Diamante",
    floating_layer_image: "Imagen",
    floating_layer_path: "Trazo",
    floating_layer_element: "Elemento",

    // Text Sidebar
    sidebar_text_title: "Texto",
    sidebar_text_desc: "Agrega texto a tu lienzo",
    add_textbox: "Agregar caja de texto",
    add_heading: "Agregar título",
    add_subheading: "Agregar subtítulo",
    add_paragraph: "Agregar párrafo",

    // Image Sidebar
    sidebar_images_title: "Imágenes",
    sidebar_images_desc: "Busca imágenes de la galería de Pixabay",
    sidebar_images_gallery_desc: "Busca imágenes de la galería de Pixabay",
    upload_image: "Subir imagen",
    // uploading already defined in Admin section
    image_uploaded: "¡Imagen subida!",
    image_upload_failed: "Error al subir imagen",
    image_fetch_failed: "Error al cargar imágenes",
    my_images: "Mis Imágenes",
    gallery_images: "Galería de Imágenes",
    powered_by_pixabay: "Provisto por Pixabay",
    no_images_yet: "Aún no hay imágenes. ¡Sube tu primera imagen!",
    refresh: "Actualizar",
    search_images: "Buscar imágenes...",
    search: "Buscar",
    search_results: "Resultados de búsqueda",
    // no_results_found already defined in Dashboard section
    clear_search: "Limpiar búsqueda",

    // Uploads Sidebar
    sidebar_uploads_title: "Mis Subidas",
    sidebar_uploads_desc: "Sube y gestiona tus propias imágenes",
    loading_uploads: "Cargando imágenes...",
    uploads_error: "Error al cargar imágenes",
    try_again: "Intentar de nuevo",
    no_uploads_yet: "Aún no hay subidas",
    upload_first_hint: "Haz clic en el botón de arriba para subir tu primera imagen",
    images_count: "imágenes",
    delete_image: "Eliminar imagen",
    image_deleted: "Imagen eliminada",
    image_delete_failed: "Error al eliminar imagen",

    // Template Sidebar
    sidebar_templates_title: "Plantillas",
    sidebar_templates_desc:
      "Elige entre una variedad de plantillas para empezar",
    templates_fetch_failed: "Error al cargar plantillas",
    confirm_replace_template_title: "¿Estás seguro?",
    confirm_replace_template_desc:
      "Estás a punto de reemplazar el proyecto actual con esta plantilla.",

    // Filter Sidebar
    sidebar_filters_title: "Filtros",
    sidebar_filters_desc: "Aplica un filtro a la imagen seleccionada",

    // Settings Sidebar
    sidebar_settings_title: "Ajustes",
    sidebar_settings_desc: "Cambia la apariencia de tu espacio de trabajo",
    resize: "Redimensionar",

    // AI Sidebar
    sidebar_ai_title: "IA",
    sidebar_ai_desc: "Genera una imagen usando IA",
    sidebar_ai_placeholder:
      "Un astronauta montando a caballo en marte, hd, iluminación dramática",
    generate: "Generar",
    ai_description: "Genera imágenes con inteligencia artificial",
    // coming_soon already defined in Templates section
    ai_coming_soon_desc:
      "La generación de imágenes con IA está en desarrollo. ¡Espera esta emocionante función!",

    // Draw Sidebar
    sidebar_draw_title: "Modo dibujo",
    sidebar_draw_desc: "Modifica los ajustes del pincel",
    brush_width: "Ancho de pincel",

    // Cookie Consent
    cookie_title: "Configuración de Cookies",
    cookie_description:
      "Usamos cookies para mejorar tu experiencia, analizar el tráfico del sitio y personalizar el contenido. Al hacer clic en 'Aceptar', consientes nuestro uso de cookies.",
    cookie_learn_more: "Más información",
    cookie_accept: "Aceptar",
    cookie_decline: "Rechazar",

    // Documentation
    docs_documentation: "Documentación",
    docs_getting_started: "Primeros Pasos",
    docs_introduction: "Introducción",
    docs_quick_start: "Inicio Rápido",
    docs_authentication: "Autenticación",
    docs_api_reference: "Referencia API",
    docs_api_overview: "Descripción General de la API",
    docs_render_endpoint: "Endpoint de Render",
    docs_templates: "Plantillas",
    docs_modifications: "Modificaciones",
    docs_formats: "Formatos de Salida",
    docs_errors: "Manejo de Errores",
    docs_guides: "Guías",
    docs_creating_templates: "Crear Plantillas",
    docs_dynamic_images: "Imágenes Dinámicas",
    docs_dynamic_text: "Texto Dinámico",
    docs_batch_processing: "Procesamiento por Lotes",
    docs_integrations: "Integraciones",
    docs_n8n: "n8n",
    docs_zapier: "Zapier",
    docs_make: "Make (Integromat)",
    docs_sdks: "SDKs y Librerías",
    docs_limits: "Límites y Precios",
    docs_rate_limits: "Límites de Tasa",
    docs_pricing: "Precios",

    // Documentation Content
    docs_intro_desc: "Bienvenido a la documentación de la API de Dynamic Canvas. Nuestra API REST te permite generar imágenes dinámicamente mediante programación, perfecto para automatizar tu flujo de trabajo de diseño a escala.",
    docs_new_here: "¿Nuevo en Dynamic Canvas?",
    docs_new_here_desc: "Comienza con nuestra guía de Inicio Rápido para hacer tu primera llamada API en minutos.",
    docs_quick_start_desc: "Comienza con Dynamic Canvas en tres simples pasos.",
    docs_step_api_key: "Obtén tu API Key",
    docs_step_api_key_desc: "Regístrate para obtener una cuenta gratuita y obtén tu API key desde el dashboard.",
    docs_step_create_request: "Crea tu primera solicitud",
    docs_step_create_request_desc: "Usa curl o cualquier cliente HTTP para hacer una solicitud de render.",
    docs_step_receive: "Recibe tu imagen generada",
    docs_step_receive_desc: "La API devuelve una URL a tu imagen generada instantáneamente.",
    docs_auth_desc: "Todas las solicitudes API requieren autenticación usando Bearer tokens. Incluye tu API key en el header Authorization de cada solicitud.",
    docs_auth_header: "Header de Autorización",
    docs_auth_header_desc: "Incluye tu API key como un Bearer token:",
    docs_security_note: "Nota de Seguridad",
    docs_security_note_desc: "Nunca expongas tu API key en código del lado del cliente o repositorios públicos. Usa variables de entorno para almacenar tu key de forma segura.",
    docs_api_overview_desc: "La API de Dynamic Canvas está organizada alrededor de REST. Nuestra API usa códigos de respuesta HTTP estándar, autenticación y verbos.",
    docs_base_url: "URL Base",
    docs_endpoints: "Endpoints Disponibles",
    docs_endpoint_render: "Generar una nueva imagen desde una plantilla",
    docs_endpoint_templates: "Listar todas las plantillas disponibles",
    docs_endpoint_template: "Obtener detalles de una plantilla específica",
    docs_endpoint_render_status: "Verificar el estado de un render",
    docs_render_desc: "El endpoint de render es el núcleo de nuestra API. Envía una solicitud POST con tu ID de plantilla y modificaciones para generar una nueva imagen.",
    docs_request_body: "Cuerpo de la Solicitud",
    docs_example_request: "Ejemplo de Solicitud",
    docs_response: "Respuesta",
    docs_templates_desc: "Las plantillas son la base de tus imágenes dinámicas. Usa el endpoint de plantillas para listar e inspeccionar las plantillas disponibles.",
    docs_modifications_desc: "Las modificaciones te permiten personalizar los elementos de la plantilla. Cada modificación apunta a un elemento específico por nombre y aplica el cambio deseado.",
    docs_mod_text: "Modificación de Texto",
    docs_mod_text_desc: "Cambia el contenido de texto de los elementos de texto en tu plantilla.",
    docs_mod_image: "Modificación de Imagen",
    docs_mod_image_desc: "Reemplaza imágenes en tu plantilla con URLs a tus propias imágenes.",
    docs_mod_color: "Modificación de Color",
    docs_mod_color_desc: "Actualiza los colores de los elementos usando códigos de color hex.",
    docs_mod_visibility: "Modificación de Visibilidad",
    docs_mod_visibility_desc: "Muestra u oculta elementos dinámicamente.",
    docs_formats_desc: "Dynamic Canvas soporta múltiples formatos de salida para satisfacer tus necesidades.",
    docs_format_png: "PNG",
    docs_format_png_desc: "Mejor para imágenes con transparencia. Compresión sin pérdida.",
    docs_format_jpg: "JPEG",
    docs_format_jpg_desc: "Mejor para fotos. Tamaño de archivo menor con compresión con pérdida.",
    docs_format_webp: "WebP",
    docs_format_webp_desc: "Formato moderno con excelente compresión. Genial para web.",
    docs_format_pdf: "PDF",
    docs_format_pdf_desc: "Perfecto para materiales impresos y documentos.",
    docs_errors_desc: "La API usa códigos de respuesta HTTP convencionales para indicar el éxito o fracaso de una solicitud.",
    docs_error_401: "Error de Autenticación",
    docs_error_401_desc: "Tu API key falta o es inválida. Verifica el header Authorization.",
    docs_error_404: "No Encontrado",
    docs_error_404_desc: "El recurso solicitado (plantilla o render) no fue encontrado.",
    docs_error_422: "Error de Validación",
    docs_error_422_desc: "El cuerpo de la solicitud contiene parámetros inválidos o campos requeridos faltantes.",
    docs_error_429: "Límite de Tasa Excedido",
    docs_error_429_desc: "Has excedido el límite de tasa de tu plan. Espera y reintenta.",
    docs_error_500: "Error del Servidor",
    docs_error_500_desc: "Ocurrió un error inesperado en nuestros servidores. Por favor intenta más tarde.",
    docs_creating_templates_desc: "Crea plantillas usando nuestro editor visual en el dashboard. Las plantillas definen el diseño base que será modificado vía API.",
    docs_template_steps: "Pasos para Crear una Plantilla",
    docs_template_step1: "Ve al Dashboard y haz clic en 'Crear Plantilla'",
    docs_template_step2: "Diseña tu plantilla usando el editor visual",
    docs_template_step3: "Nombra cada elemento que quieras modificar dinámicamente",
    docs_template_step4: "Guarda y anota tu ID de plantilla para llamadas API",
    docs_dynamic_images_desc: "Reemplaza imágenes en tus plantillas dinámicamente. Las imágenes se obtienen de URLs que proporcionas.",
    docs_supported_formats: "Formatos de Imagen Soportados",
    docs_dynamic_text_desc: "Modifica elementos de texto en tus plantillas con contenido dinámico.",
    docs_text_tips: "Mejores Prácticas para Texto Dinámico",
    docs_text_tip1: "Usa cajas de texto que puedan acomodar longitudes de texto variables",
    docs_text_tip2: "Considera el comportamiento de desbordamiento de texto en tu diseño",
    docs_text_tip3: "Prueba con contenido realista para asegurar el formato correcto",
    docs_batch_processing_desc: "Genera múltiples imágenes eficientemente iterando a través de tus datos.",
    docs_n8n_desc: "Conecta Dynamic Canvas a flujos de trabajo de n8n para automatización poderosa. Usa el nodo HTTP Request para llamar nuestra API.",
    docs_n8n_steps: "Pasos de Configuración",
    docs_n8n_step1: "Agrega un nodo HTTP Request a tu flujo de trabajo",
    docs_n8n_step2: "Establece el método a POST y la URL a nuestro endpoint de render",
    docs_n8n_step3: "Agrega tu API key en los headers y configura el body",
    docs_zapier_desc: "Integra Dynamic Canvas con más de 5000 apps usando Zapier. Crea Zaps que generen imágenes basadas en triggers de otras apps.",
    docs_make_desc: "Usa Make (antes Integromat) para crear escenarios de automatización complejos con Dynamic Canvas.",
    docs_sdks_desc: "Usa nuestros SDKs oficiales para una integración más rápida en tu lenguaje preferido.",
    docs_rate_limits_desc: "Los límites de tasa varían por plan. Exceder los límites resultará en errores 429.",
    docs_plan: "Plan",
    docs_requests_min: "Solicitudes/min",
    docs_renders_month: "Renders/mes",
    docs_free: "Gratis",
    docs_pro: "Pro",
    docs_enterprise: "Enterprise",
    docs_unlimited: "Ilimitado",
    docs_pricing_desc: "Dynamic Canvas ofrece precios flexibles para adaptarse a tus necesidades.",
    docs_pricing_info: "Visita la página de precios en nuestro sitio web para información detallada de planes y funciones.",

    // Legal Pages
    privacy_policy: "Política de Privacidad",
    terms_title: "Términos de Servicio",
    last_updated: "Última actualización",
    back_to_home: "Volver al inicio",

    // Privacy Policy
    privacy_intro_title: "Introducción",
    privacy_intro_desc:
      "En Dynamic Canvas nos tomamos tu privacidad muy en serio. Esta Política de Privacidad explica cómo recopilamos, usamos, divulgamos y protegemos tu información cuando utilizas nuestra plataforma de automatización de diseño y servicios API.",
    privacy_collect_title: "Información que Recopilamos",
    privacy_collect_desc:
      "Podemos recopilar información sobre ti de varias maneras:",
    privacy_collect_name: "Nombre e información de contacto al crear una cuenta",
    privacy_collect_email: "Dirección de correo electrónico para verificación y comunicaciones",
    privacy_collect_usage: "Datos de uso incluyendo plantillas creadas y renders generados",
    privacy_collect_api: "Estadísticas de uso de API y registros para mejorar el servicio",
    privacy_collect_device: "Información del dispositivo y navegador para fines de seguridad",
    privacy_use_title: "Cómo Usamos tu Información",
    privacy_use_desc:
      "Utilizamos la información que recopilamos para los siguientes propósitos:",
    privacy_use_service: "Proporcionar y mantener nuestros servicios de automatización de diseño",
    privacy_use_communicate: "Comunicarnos contigo sobre actualizaciones, funciones y soporte",
    privacy_use_improve: "Mejorar nuestra plataforma y desarrollar nuevas funciones",
    privacy_use_security: "Detectar y prevenir fraudes, abusos y problemas de seguridad",
    privacy_storage_title: "Almacenamiento y Seguridad de Datos",
    privacy_storage_desc:
      "Implementamos medidas de seguridad técnicas y organizativas apropiadas para proteger tu información personal. Tus datos se almacenan en servidores seguros con cifrado en reposo y en tránsito. Conservamos tu información solo el tiempo necesario para proporcionar nuestros servicios.",
    privacy_rights_title: "Tus Derechos",
    privacy_rights_desc:
      "Tienes ciertos derechos con respecto a tu información personal:",
    privacy_rights_access: "Acceso: Solicitar una copia de tus datos personales",
    privacy_rights_correct: "Corrección: Solicitar la corrección de datos inexactos",
    privacy_rights_delete: "Eliminación: Solicitar la eliminación de tus datos",
    privacy_rights_export: "Exportación: Recibir tus datos en formato portátil",
    privacy_cookies_title: "Cookies y Seguimiento",
    privacy_cookies_desc:
      "Utilizamos cookies y tecnologías de seguimiento similares para mejorar tu experiencia en nuestra plataforma. Puedes controlar las preferencias de cookies a través de la configuración de tu navegador. Usamos cookies de sesión y persistentes para autenticación, preferencias y análisis.",
    privacy_third_title: "Servicios de Terceros",
    privacy_third_desc:
      "Podemos utilizar servicios de terceros para procesamiento de pagos, análisis e infraestructura. Estos proveedores tienen sus propias políticas de privacidad y solo compartimos la información necesaria para que puedan proporcionar sus servicios.",
    privacy_children_title: "Privacidad de Menores",
    privacy_children_desc:
      "Nuestros servicios no están dirigidos a menores de 16 años. No recopilamos conscientemente información personal de niños. Si crees que hemos recopilado información de un menor, por favor contáctanos.",
    privacy_changes_title: "Cambios en Esta Política",
    privacy_changes_desc:
      "Podemos actualizar esta Política de Privacidad periódicamente. Te notificaremos sobre cualquier cambio publicando la nueva Política de Privacidad en esta página y actualizando la fecha de 'Última actualización'.",
    privacy_contact_title: "Contáctanos",
    privacy_contact_desc:
      "Si tienes preguntas sobre esta Política de Privacidad, contáctanos en:",

    // Terms of Service
    terms_intro_title: "Acuerdo de Términos",
    terms_intro_desc:
      "Estos Términos de Servicio constituyen un acuerdo legalmente vinculante entre tú y Dynamic Canvas con respecto al uso de nuestra plataforma de automatización de diseño, servicios API y funciones relacionadas.",
    terms_acceptance_title: "Aceptación de Términos",
    terms_acceptance_desc:
      "Al acceder o usar Dynamic Canvas, aceptas estar sujeto a estos Términos. Si no estás de acuerdo con alguna parte de los términos, no puedes acceder al servicio.",
    terms_service_title: "Descripción del Servicio",
    terms_service_desc:
      "Dynamic Canvas proporciona una plataforma de automatización de diseño que incluye:",
    terms_service_templates: "Herramientas de creación y edición de plantillas",
    terms_service_api: "API REST para generación programática de imágenes",
    terms_service_renders: "Renderizado dinámico de diseños con datos personalizados",
    terms_service_storage: "Almacenamiento en la nube para plantillas e imágenes generadas",
    terms_accounts_title: "Cuentas de Usuario",
    terms_accounts_desc:
      "Eres responsable de proteger la contraseña que usas para acceder al servicio:",
    terms_accounts_accurate: "Proporcionar información precisa y completa durante el registro",
    terms_accounts_security: "Mantener la seguridad de las credenciales de tu cuenta",
    terms_accounts_responsible: "Asumir la responsabilidad de todas las actividades bajo tu cuenta",
    terms_usage_title: "Uso Aceptable",
    terms_usage_desc:
      "Aceptas no usar el servicio para ningún propósito ilegal o de manera que pueda dañar, deshabilitar o deteriorar el servicio. Las actividades prohibidas incluyen:",
    terms_usage_illegal: "Violar leyes o regulaciones aplicables",
    terms_usage_harmful: "Distribuir malware o código dañino",
    terms_usage_infringe: "Infringir derechos de propiedad intelectual de terceros",
    terms_usage_malicious: "Intentar obtener acceso no autorizado a sistemas",
    terms_usage_reverse: "Ingeniería inversa o intentar extraer código fuente",
    terms_usage_spam: "Usar el servicio para enviar spam o comunicaciones no solicitadas",
    terms_ip_title: "Propiedad Intelectual",
    terms_ip_desc:
      "El servicio y su contenido original, funciones y características son propiedad de Dynamic Canvas:",
    terms_ip_platform: "La plataforma, software y tecnología subyacente pertenecen a Dynamic Canvas",
    terms_ip_content: "Conservas la propiedad del contenido que creas y subes",
    terms_ip_renders: "Los renders generados de tus plantillas te pertenecen",
    terms_payment_title: "Términos de Pago",
    terms_payment_desc:
      "Algunas funciones requieren pago. Aceptas proporcionar información de facturación precisa y nos autorizas a cargar tu método de pago elegido por el plan seleccionado. Todas las tarifas son no reembolsables excepto según lo exija la ley.",
    terms_cancellation_title: "Cancelación y Terminación",
    terms_cancellation_desc:
      "Puedes cancelar tu cuenta en cualquier momento. Al cancelar, tu acceso a las funciones de pago terminará al final del período de facturación actual. Podemos suspender o terminar tu cuenta por violaciones de estos Términos.",
    terms_limitation_title: "Limitación de Responsabilidad",
    terms_limitation_desc:
      "Dynamic Canvas no será responsable de ningún daño indirecto, incidental, especial, consecuente o punitivo resultante de tu uso o incapacidad de usar el servicio.",
    terms_modifications_title: "Modificaciones",
    terms_modifications_desc:
      "Nos reservamos el derecho de modificar estos Términos en cualquier momento. Proporcionaremos aviso de cambios significativos. Tu uso continuado del servicio después de los cambios constituye la aceptación de los Términos modificados.",
    terms_governing_title: "Ley Aplicable",
    terms_governing_desc:
      "Estos Términos se regirán e interpretarán de acuerdo con las leyes aplicables, sin tener en cuenta las disposiciones de conflicto de leyes.",
    terms_contact_title: "Contáctanos",
    terms_contact_desc:
      "Para preguntas sobre estos Términos, contáctanos en:",

    // Security Page
    security_title: "Seguridad",
    security_intro_title: "Nuestro Compromiso con la Seguridad",
    security_intro_desc:
      "En Dynamic Canvas, la seguridad es una prioridad máxima. Implementamos prácticas de seguridad líderes en la industria para proteger tus datos y garantizar la confiabilidad de nuestra plataforma de automatización de diseño.",
    security_infrastructure_title: "Seguridad de Infraestructura",
    security_infrastructure_desc:
      "Nuestra infraestructura está construida con la seguridad en mente:",
    security_infrastructure_hosting: "Alojamiento en la nube seguro con proveedores líderes",
    security_infrastructure_encryption: "Cifrado en reposo y en tránsito para todos los datos",
    security_infrastructure_backups: "Copias de seguridad automatizadas regulares con almacenamiento seguro",
    security_infrastructure_monitoring: "Sistemas de monitoreo y alertas 24/7",
    security_api_title: "Seguridad de API",
    security_api_desc:
      "Nuestra API está diseñada con múltiples capas de seguridad:",
    security_api_keys: "Autenticación con API keys seguras y permisos limitados",
    security_api_https: "Todas las comunicaciones API usan cifrado HTTPS/TLS",
    security_api_rate: "Limitación de tasa para prevenir abusos y garantizar uso justo",
    security_api_audit: "Registro de auditoría completo de todas las solicitudes API",
    security_data_title: "Protección de Datos",
    security_data_desc:
      "Protegemos tus datos a través de múltiples medidas:",
    security_data_rest: "Cifrado en reposo usando AES-256",
    security_data_transit: "Cifrado en tránsito usando TLS 1.3",
    security_data_retention: "Políticas de retención de datos configurables",
    security_data_deletion: "Eliminación segura de datos a solicitud",
    security_access_title: "Control de Acceso",
    security_access_desc:
      "Implementamos controles de acceso estrictos:",
    security_access_authentication: "Autenticación de múltiples factores disponible",
    security_access_authorization: "Control de acceso basado en roles (RBAC)",
    security_access_least: "Principio de menor privilegio para todo acceso",
    security_access_logging: "Registro y monitoreo completo de acceso",
    security_compliance_title: "Cumplimiento",
    security_compliance_desc:
      "Mantenemos cumplimiento con estándares de la industria:",
    security_compliance_gdpr: "Cumplimiento con GDPR para protección de datos de la UE",
    security_compliance_soc: "Certificación SOC 2 Tipo II en proceso",
    security_compliance_pci: "Procesamiento de pagos cumpliendo con PCI DSS",
    security_incident_title: "Respuesta a Incidentes",
    security_incident_desc:
      "Nuestro proceso de respuesta a incidentes incluye:",
    security_incident_detection: "Detección y evaluación rápida",
    security_incident_response: "Respuesta y contención inmediata",
    security_incident_notification: "Notificación transparente a usuarios afectados",
    security_incident_post: "Revisión post-incidente y mejoras",
    security_vulnerability_title: "Divulgación Responsable",
    security_vulnerability_desc:
      "Damos la bienvenida a los investigadores de seguridad para reportar vulnerabilidades de manera responsable. Si descubres un problema de seguridad, repórtalo a nuestro equipo de seguridad con detalles. Estamos comprometidos a abordar las preocupaciones de seguridad legítimas prontamente.",
    security_contact_title: "Contacto de Seguridad",
    security_contact_desc:
      "Para reportar un problema de seguridad o consultas relacionadas con seguridad, contáctanos en:",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [language, setLanguage] = useState<Language>("es"); // Default to Spanish as requested implementation implies interest

  // Load from local storage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "es")) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: handleSetLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
